skedgo/tripkit-android

CommonCoreLegacy/src/main/java/skedgo/tripkit/routing/TripSegment.java

- Add safe metres properties, https://redmine.buzzhives.com/issues/8321#note-15

Add metresUnsafe into TripSegment 

---

route-persistence/src/main/java/com/skedgo/routepersistence/RouteStore.java

This PR fixes a bug in RouteStore that omit loading the first TripSegment.

Fix leave segment not loaded 

---

CommonCoreLegacy/src/main/java/com/skedgo/android/common/model/ServiceStop.java
CommonCoreLegacy/src/main/java/com/skedgo/android/common/model/WheelchairAccessible.kt

- Add WheelchairAccessible interface to use case reuse.

Add WheelchairAccessible interface

---

TripKitAndroid/src/main/java/skedgo/tripkit/a2brouting/A2bRoutingDataModule.kt
ValidBookingCountData/build.gradle

- Increase read timeout for routing API
- https://redmine.buzzhives.com/issues/8900

Increase read timeout for A2bRoutingApi

---

AccountData/build.gradle
CommonCoreLegacy/build.gradle
TripKitAndroid/build.gradle
TripKitData/build.gradle
TripKitDomain/build.gradle
TripKitDomainLegacy/build.gradle
ValidBookingCountData/build.gradle

This PR remove immutables library from packaging.

Remove immutables

---

CommonCoreLegacy/src/main/java/com/skedgo/android/common/util/TripSegmentUtils.java
CommonCoreLegacy/src/main/java/skedgo/tripkit/routing/RoutingResponse.java
CommonCoreLegacy/src/main/java/skedgo/tripkit/routing/SegmentActionTemplates.java
CommonCoreLegacy/src/main/java/skedgo/tripkit/routing/SegmentJsonKeys.java
CommonCoreLegacy/src/main/java/skedgo/tripkit/routing/SegmentNotesTemplates.java
CommonCoreLegacy/src/test/java/com/skedgo/android/common/util/TripSegmentUtilsTest.kt

Fix issue https://redmine.buzzhives.com/issues/8971

Fix missing space issue

---

TripKitSamples/build.gradle
build.gradle
dependencies.gradle
trip-kit-booking-ui/build.gradle

Upgrade to Android Gradle plugin v3.0.1

---

TripKitSamples/build.gradle
dependencies.gradle
trip-kit-booking-ui/build.gradle
trip-kit-booking-ui/src/main/java/com/skedgo/android/tripkit/booking/ui/activity/BookingActivity.kt

@duduct (Design team) requested a year ago or so.

Remove ActivityAnimations library

---

CommonCoreLegacy/src/main/java/com/skedgo/android/common/util/TimeUtils.java

As a result of `RouteLocationDataSource` being deleted

Remove unused nextLong()

---

AccountDomain/build.gradle
CommonCoreLegacy/src/main/java/com/skedgo/android/common/model/RealtimeAlert.java
TripKitAndroid/src/main/java/com/skedgo/android/tripkit/alerts/AlertBlock.java
TripKitAndroid/src/main/java/com/skedgo/android/tripkit/alerts/RealtimeAlertService.java
TripKitAndroid/src/main/java/com/skedgo/android/tripkit/alerts/Route.java
ValidBookingCountDomain/build.gradle

Implements https://redmine.buzzhives.com/issues/9447

Implement service alerts

---

CommonCoreLegacy/src/main/java/skedgo/tripkit/routing/LocationExtensions.kt
CommonCoreLegacy/src/main/java/skedgo/tripkit/routing/TripExtensions.kt
CommonCoreLegacy/src/test/java/skedgo/tripkit/routing/TripExtensionsKtTest.kt

- Get trip plain text description. Issue https://redmine.buzzhives.com/issues/9462?issue_count=33&issue_position=2&next_issue_id=9458&prev_issue_id=9463

Trip plain text

---

TripKitAndroid/src/main/java/com/skedgo/android/tripkit/DefaultModeFilter.kt
TripKitAndroid/src/main/java/com/skedgo/android/tripkit/ModeFilter.kt
TripKitAndroid/src/main/java/com/skedgo/android/tripkit/QueryGeneratorImpl.java
TripKitAndroid/src/main/java/com/skedgo/android/tripkit/RouteServiceImpl.java
TripKitAndroid/src/main/java/skedgo/tripkit/a2brouting/RouteService.kt
TripKitAndroid/src/main/java/skedgo/tripkit/a2brouting/SingleRouteService.java
TripKitAndroid/src/test/java/com/skedgo/android/tripkit/QueryGeneratorImplTest.java
TripKitAndroid/src/test/java/com/skedgo/android/tripkit/RouteServiceImplTest.java
TripKitAndroid/src/test/java/skedgo/tripkit/a2brouting/SingleRouteServiceTest.java

Add modeFilter param to routing service

Support modes filter

---

CommonCoreLegacy/src/main/java/skedgo/tripkit/routing/RealTimeVehicle.java

https://redmine.buzzhives.com/issues/9900

Fix bus occupacy

---

CommonCoreLegacy/src/main/java/skedgo/tripkit/routing/VehicleMode.java
CommonCoreLegacy/src/main/res/drawable/ic_icon_mode_funicular.xml

- Public transport funicular icon added

Add funicular icon

---

TripKitAndroid/build.gradle
TripKitAndroid/src/main/java/com/skedgo/android/tripkit/MainModule.java
TripKitAndroid/src/main/java/com/skedgo/android/tripkit/RegionServiceImpl.kt
TripKitAndroid/src/main/java/com/skedgo/android/tripkit/RouteServiceImpl.java
TripKitAndroid/src/main/java/com/skedgo/android/tripkit/tsp/RegionInfoRepository.kt
TripKitAndroid/src/test/java/com/skedgo/android/tripkit/RegionServiceImplTest.kt
TripKitAndroid/src/test/java/com/skedgo/android/tripkit/RouteServiceImplTest.java

- Implement region info cache and fix wheelchair mode stuck issue, https://redmine.buzzhives.com/issues/10074

Region info cache

---

CommonCoreLegacy/src/main/java/com/skedgo/android/common/model/ServiceStop.java

Remove deprecated getDisplayTime

Remove deprecated getDisplayTime

---

AccountData/build.gradle
CommonCoreLegacy/build.gradle
TripKitAndroid/build.gradle
TripKitData/build.gradle
TripKitDomainLegacy/build.gradle
ValidBookingCountData/build.gradle
build.gradle
route-persistence/build.gradle
trip-kit-booking-ui/build.gradle
trip-kit-booking/build.gradle

Reverts skedgo/tripkit-android#354 - I didn't realize there's already a fix for this in dev

Revert "The ancient maven plugin broke, switch to a modern one"

---

CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/TripSegment.java
CommonCoreLegacy/src/main/res/drawable/ic_wifi.xml

[18683] Updated realtime handling for the trip segment list item ui

https://redmine.buzzhives.com/issues/18683

---

CommonCoreLegacy/build.gradle
TripKitAndroid/build.gradle
TripKitData/build.gradle
TripKitData/src/main/AndroidManifest.xml
TripKitDomain/build.gradle
TripKitDomainLegacy/build.gradle
ValidBookingCountData/build.gradle
ValidBookingCountDomain/src/main/java/com/skedgo/tripkit/validbookingcount/domain/GetRemoteValidBookingCount.kt
dependencies.gradle
gradle/wrapper/gradle-wrapper.properties
trip-kit-booking-ui/build.gradle
trip-kit-booking/build.gradle

[19335] Update dependencies.gradle to run on latest JDK

https://redmine.buzzhives.com/issues/19335

---

trip-kit-booking/src/main/java/com/skedgo/tripkit/booking/quickbooking/QuickBookResponse.kt

[19528] Payment method selection handling

https://redmine.buzzhives.com/issues/19528

---

TripKitAndroid/src/main/java/com/skedgo/tripkit/routing/GeofenceBroadcastReceiver.kt

[odin_1.0.73] Playstore reject fixes

Release ODIN 1.0.73 

---

CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/Trip.java
TripKitAndroid/src/main/java/com/skedgo/tripkit/MainModule.java

[19765] Added and initial configuration for the new NEC WL. Get off alert fix if saveURL is null for Trip.
[19823] Kill switch implementation

https://redmine.buzzhives.com/issues/19765 and https://redmine.buzzhives.com/issues/19823

---

CommonCoreLegacy/src/main/java/com/skedgo/tripkit/common/model/Street.java
CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/RoadTag.kt
CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/TripKitMapTiles.kt
CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/TripSegment.java
TripKitAndroid/src/main/java/com/skedgo/tripkit/LineSegment.java
TripKitAndroid/src/main/java/com/skedgo/tripkit/a2brouting/GetNonTravelledLineForTrip.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/a2brouting/GetTravelledLineForTrip.kt

Map Tiles & Road Tags handling

https://redmine.buzzhives.com/issues/19696

---

TripKitAndroid/src/main/java/com/skedgo/TripKit.java
TripKitAndroid/src/main/java/com/skedgo/tripkit/ErrorHandlingInterceptor.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/HttpClientModule.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/TripKitConstants.kt

[19823] put the app deactivated checker on http module to catch 401 error for all the APIs

[19823] App deactivation handling when tripgo key is suspended or invalid

---

trip-kit-booking/src/main/java/com/skedgo/tripkit/booking/quickbooking/ConfirmPaymentUpdateResponse.kt
trip-kit-booking/src/main/java/com/skedgo/tripkit/booking/quickbooking/QuickBookResponse.kt
trip-kit-booking/src/main/java/com/skedgo/tripkit/booking/quickbooking/QuickBookingApi.kt
trip-kit-booking/src/main/java/com/skedgo/tripkit/booking/quickbooking/QuickBookingService.kt

Fix payment handling for INTERNAL and EXTERNAL payment mode

---

CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/Trip.java
TripKitAndroid/src/main/java/com/skedgo/tripkit/OnSubscribeReverseGeocode.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/TripUpdateApi.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/TripUpdater.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/TripUpdaterImpl.kt
dependencies.gradle
route-persistence/src/main/java/com/skedgo/routepersistence/RouteContract.java
route-persistence/src/main/java/com/skedgo/routepersistence/RouteDatabaseHelper.java
route-persistence/src/main/java/com/skedgo/routepersistence/RouteStore.kt

- Updated targetSdkVersion to 33 for notification permission validation on android > 33
- Allow notification permission checking on app open and on turning on trip notification feature
- Handle additional subscribeURL and unsubscribeURL fields in trip
- add subscribeURL and unsubscribeURL fields to local db
- call subscribeURL when trip notification is turned on and unsubscribeURL when turned off

[19952] Subscribe/Unsubscribe trip notifications

---

CommonCoreLegacy/src/main/java/com/skedgo/tripkit/common/model/BookingConfirmationAction.java
CommonCoreLegacy/src/main/java/com/skedgo/tripkit/common/model/BookingConfirmationStatusValue.kt
dependencies.gradle
trip-kit-booking/src/main/java/com/skedgo/tripkit/booking/quickbooking/QuickBookResponse.kt

- Handle Review list items for payment summary
- drt adjustments to handle action type SHOW_RELATED_TRIP and redirect user to the trip fetched using interalURL
- Booking list pager for Valid and Expired list. 
- Booking list lazy loading using paging library. 
- Loader indicator. 
- Booking list trip load on click
- Booking list item UI update. 
- Include bookings from relatedBookings in MyBooking list and tag as Return trip.

[19780] Booking and My Bookings revisions

---

CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/GetOffAlertCache.kt
CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/TripExtensions.kt

- Create NextUpItemManager and NextUpItem to add card on home
- Renamed TripPreviewHeader to TripSegmentSummary and update classes using it. 
- Create TripGoSharedPreference to centralize handling TripGo data using SharedPreference

[20162] Next Up item card feature on home

---

TripKitAndroid/build.gradle
TripKitAndroid/src/main/java/com/skedgo/TripKit.java
TripKitAndroid/src/main/java/com/skedgo/tripkit/TripKitConstants.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/data/BaseSharedPreference.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/data/TripKitPreferencesModule.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/data/TripKitSharedPreference.kt
TripKitAndroid/src/test/java/com/skedgo/tripkit/data/TripKitSharedPreferenceTest.kt

**Changes**
- [TripKitUI] Focus map to selected client's region
- [TripGoSdk] Update TripGoSharedPreference to make it injectable and not initialized by application context to avoid memory leakage.
- [TripKit] Create TripKitSharedPreference to centralize handling SharePreference logic for TripKit
- [TripGoSdk & TripKit] Setup MockK
- [TripGoSdk] Written unit test for the new TripGoSharedPreference class
- [TripKit] Written unit test for the new TripKitSharedPreference class
**Unit Test**

[19730] Region selected focus

---

dependencies.gradle

**Changes**
[19947]
- [TripKitUI] Showing Crowdiness on Trip details segment. 
- [TripKitUI] Minor ui adjustments on road tags
- [TripKitUI] Add Trip summary preview on Trip details
- [TripKit] Add coroutines test dependency
[20385]
- [TripKitUI] Fix RoadTags and Occupancy getting duplicated when creating stationary item on trip segments in Trip details view
[20406]
- [TripKitUI] Fix scrolling issue on TripDetails due to BottomSheet, ViewPager and Recyclerview touch conflicts

[19947] Add Crowdiness on trip segment if realtimeVehicle is available [20385] Duplicate RoadTag fix [20406] Scrolling conflict fix

---

CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/RoadTag.kt

[TripKit] Update RoadTags and add Lit-Route to handle it on app

[20391] Handle Lit Route road tag

---

CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/Geofence.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/Configs.java
TripKitAndroid/src/main/java/com/skedgo/tripkit/LocationUtils.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/routing/GeoLocation.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/routing/GeofenceBroadcastReceiver.kt
TripKitAndroid/src/main/java/com/skedgo/tripkit/routing/GeofenceUtils.kt

- [TripKit] Update GeofenceBroadcastReceiver pendingIntent to fix adding data that displaces existing data within the intent.
- [TripKit] Fix geofence expiration time computation.
- [TripKit] Fix setting geofence transition type
- [TripKitUI] Showing circle on map as geofence indicator, for debugging purposes 
- [TripGov5&TripKit] Adding config to enable showing geofences on debug mode 
- [TripKitUI] Added checking to show pop-up message when device location is turned off when user switched on Trip notification toggle.

[20464] Destination notification fix

---

.github/PULL_REQUEST_TEMPLATE.md

Introducing `PULL_REQUEST_TEMPLATE.md` to enhance the quality and consistency of PR submissions. This template ensures all necessary details are included for an efficient review process.
```markdown
- **Type**: (Bug Fix / Feature / Refactor / Regression Fix)
- **Issue Link**: [Issue](https://redmine.buzzhives.com/issues/[XXXXX])
- **Risk Factor**: (Low / Medium / High)
- Detailed description of changes.
- Documentation and Code Quality
- Testing and Reliability
- Error Handling and Logging
- Steps for testing the changes.
- List of unfinished tasks.

[PR-REQUEST-FORMAT] Created a format to be followed when creating PR request

---

CommonCoreLegacy/src/main/java/com/skedgo/tripkit/common/model/ScheduledStop.java
CommonCoreLegacy/src/main/java/com/skedgo/tripkit/common/model/ServiceStop.java
CommonCoreLegacy/src/main/java/com/skedgo/tripkit/common/model/WheelchairAccessible.kt
CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/TripSegment.java
CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/VehicleMode.java
TripKitData/src/main/java/com/skedgo/tripkit/data/database/DbFields.java
TripKitData/src/main/java/com/skedgo/tripkit/data/database/DbHelper.java
TripKitData/src/main/java/com/skedgo/tripkit/data/database/DbTables.java
TripKitData/src/main/java/com/skedgo/tripkit/data/database/stops/StopLocationEntity.kt

- [TripKitUI] update CursorToServiceConverter to add bicycleAccessible handling
- [TripKit] update DbFields and add BICYCLE_ACCESSIBLE db field
- [TripKit] update DbHelper to add migrator for service and service_stops table to handle new bicycle_accessible column
- [TripKit] update DatabaseTable and add bicycle_accessible field for service and service_stops
- [TripKitUI] update dimens.xml to add service detail icon size
- [TripKitUI] update FetchService and add handling for BicycleAccessible
- [TripKitUI] update GetWheelchairAccessible and rename to GetModeAccessibility to add bicycle value handling
- [TripKitUI] update GetStopsByTravelType and add bicycleAccessible handling
- [TripGov5][TripKitUI] add ic_bike and ic_bike_accessible.xml icons
- [TripKit] update ScheduledStop and add …

[20771] Bicycle Accessible icon and label handling

---

TripKitData/src/main/java/com/skedgo/tripkit/data/database/TripKitDatabase.kt
TripKitData/src/main/java/com/skedgo/tripkit/data/database/locations/facility/FacilityDao.kt
TripKitData/src/main/java/com/skedgo/tripkit/data/database/locations/facility/FacilityLocationEntity.kt
TripKitData/src/main/java/com/skedgo/tripkit/data/database/locations/facility/FacilityRepository.kt
TripKitData/src/main/java/com/skedgo/tripkit/data/database/locations/facility/FacilityRepositoryImpl.kt
TripKitData/src/main/java/com/skedgo/tripkit/data/locations/LocationsResponse.java
TripKitData/src/main/java/com/skedgo/tripkit/data/locations/StopsFetcher.kt

- [TripKitUI] add Marker provider, CreateMarkerFoFacility, for facility
- [TripKitUI] update DefaultLoadPOILocationsByViewPort and add loading of facilities within bounds
- [TripKit] add FacilityDao to handle room db related transactions
- [TripKit] add FacilityLocationEntity model to handle facility data from location.json response
- [TripKitUI] add FacilityPOILocation, POI handling, for facility
- [TripKit] add FacilityRepository and FacilityRepositoryImpl to handle communication with room db for saving and loading facilities
- [TripKitUI] add LoadFacilitiesByViewPort for loading facilities by view port
- [TripKit] update LocationsResponse and added field for facilities
- [TripKitUI] add MarkerIconManager to process drawable and convert it to bitmap to use as marker using application …

[20911] Handle Facilities from location.json

---

trip-kit-booking/src/main/java/com/skedgo/tripkit/booking/quickbooking/QuickBooking.kt
trip-kit-booking/src/main/java/com/skedgo/tripkit/booking/quickbooking/QuickBookingType.kt

**Details:** Support for new type of mobility option for T&C on Android
**Link:** https://redmine.buzzhives.com/issues/20606

[20606] Included support for terms and conditions type of mobility

---

dependencies.gradle

**Details:** Prepare for AWS Amplify SDK as alternative to Auth0 SDK on Android
**Link:** https://redmine.buzzhives.com/issues/20502

[20502] Updated dependencies gradle to add aws amplify cognito

---

TripKitAndroid/src/main/java/com/skedgo/tripkit/ModeCombinationStrategy.java

https://redmine.buzzhives.com/issues/21254
- [TripKit] update logic for matching modeId to modeMap in ModeCombinationStrategy

[21254] Group `pt_modes=pt_ltd_SCHOOLBUS_*` into a single request

---

trip-kit-booking/src/main/java/com/skedgo/tripkit/booking/quickbooking/QuickBookingType.kt

**Detail:** Support for new type of mobility option for T&C on Android
**Link:** https://redmine.buzzhives.com/issues/20606

[20606] Revised terms and conditions handling

---

CommonCoreLegacy/src/main/java/com/skedgo/tripkit/routing/RemoteIcon.kt

https://redmine.buzzhives.com/issues/20787
- [TripKitUI] update GetRealtimeText to include logic if hour and minutes are the same
- [TripKitUI] TripSegmentItemViewModel code cleanup

 [20787] Fix schedule checking

---

.github/workflows/auto_stale_pr.yml

**Ticket:** PR Automated Stale Github Action
**Link:** https://redmine.buzzhives.com/issues/20366
**Implement Reference:** https://github.com/marketplace/actions/close-stale-issues
> Note: Proven and tested working, updated restrictions (Will also be merged to master after)

[20366] Updated Auto Stale PR logic to reflect correct restrictions
